AllCops:
  TargetRubyVersion: 2.3

CyclomaticComplexity:
  Enabled: false

LineLength:
  Max: 115

Documentation:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 25
  Exclude:
    - test/**/*.rb

FrozenStringLiteralComment:
  Enabled: false

AbcSize:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
